name: Build api

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build binary and push (api)
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - name: Setup environment
      #   run: |
      #     echo "SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      #     echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_ENV
      # - name: Copy binary
      #   run: mv target/release/api api/api
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Login to repository
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test matrix output
        run: echo "$MATRIX_ENV"
        env:
          MATRIX_ENV: ${{ matrix }}
      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     platforms: linux/arm64
      #     context: apps/api
      #     file: apps/api/Dockerfile
      #     tags: docker.moonclient.dev/api:git-${{ env.BRANCH_NAME }}-${{ env.SHORT_COMMIT_SHA }}
